export const CLIENT_SET_USER = 'CLIENT_SET_USER';
export const CLIENT_SET_ROLES = 'CLIENT_SET_ROLES';
export const CLIENT_SET_THEME = 'CLIENT_SET_THEME';
export const CLIENT_SET_LANGUAGE = 'CLIENT_SET_LANGUAGE';
export const CLIENT_SET_ADDRESS_LIST = 'CLIENT_SET_ADDRESS_LIST';
export const CLIENT_SET_CREDIT_CARDS = 'CLIENT_SET_CREDIT_CARDS';

export const PRODUCT_SET_CATEGORIES = 'PRODUCT_SET_CATEGORIES';
export const PRODUCT_SET_PRODUCT_LIST = 'PRODUCT_SET_PRODUCT_LIST';
export const PRODUCT_SET_TOTAL = 'PRODUCT_SET_TOTAL';
export const PRODUCT_SET_FETCH_STATE = 'PRODUCT_SET_FETCH_STATE';
export const PRODUCT_SET_LIMIT = 'PRODUCT_SET_LIMIT';
export const PRODUCT_SET_OFFSET = 'PRODUCT_SET_OFFSET';
export const PRODUCT_SET_FILTER = 'PRODUCT_SET_FILTER';

export const CART_SET_CART = 'CART_SET_CART';
export const CART_SET_PAYMENT = 'CART_SET_PAYMENT';
export const CART_SET_ADDRESS = 'CART_SET_ADDRESS';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_UPDATE_ITEM_COUNT = 'CART_UPDATE_ITEM_COUNT';
export const CART_TOGGLE_ITEM = 'CART_TOGGLE_ITEM';
export const CART_CLEAR = 'CART_CLEAR';
